### ISSUE TITLE
Change convention of commit summary to not use square brackets

### ISSUE THREAD

**Issue by knocte** [meebey/smuxi#145]
The convention that Smuxi uses for its commit messages makes it not very git-am friendly, because if you extract a patch via `git format-patch HEAD~1`, and you apply it again via `git am 0001-*.patch`, this is what happens:

    $ head -4 0002-Engine-Twitter-Delay-the-UI-usage-in-the-timeline-co.patch 
    From 841eca3a2fd5759e62eb7978e4d2a1c9f8dc7113 Mon Sep 17 00:00:00 2001
    From: =?UTF-8?q?Andr=C3=A9s=20G=2E=20Aragoneses?= <knocte@gmail.com>
    Date: Thu, 14 Nov 2013 23:02:35 +0100
    Subject: [PATCH 2/2] [Engine-Twitter] Delay the UI usage in the timeline
    $ git am 0002-Engine-Twitter-Delay-the-UI-usage-in-the-timeline-co.patch 
    Applying: Delay the UI usage in the timeline command
    $ git log | head -5
    commit 39853f9a227e86cdce3c832923e74d1d361bb865
    Author: Andrés G. Aragoneses <knocte@gmail.com>
    Date:   Thu Nov 14 23:02:35 2013 +0100
        Delay the UI usage in the timeline command

As you can see above, the [Engine-Twitter] string disappears.

You may think that this is only useful for people who exchange patches via email. But in this case it was just me working on refactoring a pull request: I had 3 commits in a PR, and I had to change the 2nd of the commits. To do that, I extracted the last 2 via `git format-patch`, to be able to apply the last one (via `git am`), and ammend the 2nd to be the last one.

Because of this issue, my workflow had to be a bit more complicated and I was frustrated.

Other projects, when switching to use git, have changed their HACKING guidelines. For example, the Gnome project uses what the Git conventions say, instead of "[Foo] bla bla bla", they use "Foo: bla bla bla"

**Comment by meebey** [comment]
Already implemented and used for over a year, thus closing.
