### ISSUE TITLE
Link highlighting stops at upper-case I letter

### ISSUE THREAD

**Issue by huseyint** [meebey/smuxi#183]
Hi. This is probably due to my Windows with Turkish regional settings. When a link with upper case I letter is rendered, the underline stops at that position, see the following image:

![](http://i.imgur.com/LEa1BWo.png)

See the following posts about the Turkish lower/upper case ı/İ issue:

http://blog.codinghorror.com/whats-wrong-with-turkey/
http://www.moserware.com/2008/02/does-your-code-pass-turkey-test.html
##

**Comment by dbech** [comment]
I tried this out with the same link using english us and it appears to work

<img src="http://puu.sh/ogP3n/ca421d101b.png">

**Comment by meebey** [comment]
Smuxi uses a character class [a-z] with case insensitive modifier as regex to match the URL. I am not sure if the issue still applies since I don't have a sample of the verbatim text, but a screenshot I can't copy/paste to test it myself...

**Comment by meebey** [comment]
Closing because the issue is not reproducible and inactivity of the issue report. Please re-open this issue if you can still observe the problem.
