### ISSUE TITLE
Object must implement IConvertible

### ISSUE THREAD

**Issue by altyr** [meebey/smuxi#199]
Has there been any progress on [Bug 589](https://smuxi.im/issues/show/589)?
Things work fine when using a Linux-based client, but i every time i try connecting to smuxi-server from windows this happens: https://gist.github.com/altyr/fcf98b653e08f9203ccd#file-smuxiiconvertible
Are there any workarounds?
##

**Comment by meebey** [comment]
Since Smuxi 1.0.4 the Windows installer includes a Mono detection and creates a Smuxi (Mono) shortcut automatically to run Smuxi on the Mono runtime.

**Comment by meebey** [comment]
Since the 1.0.6 release, Smuxi will show an incompatibility warning with a link how to fix the issue
