### ISSUE TITLE
XMPP: Nickname für conference rooms

### ISSUE THREAD

**Issue by nbartels** [meebey/smuxi#214]
With other xmpp clients, I'm able to set a different nick name at least in conference rooms.

I changed the general preferences' nickname/username/realname but get still the login name if I use a xmpp-server.

Would be nice to know if it is possible to change the name in smuxi. Or add it, it this feature is missing :smile:

**Comment by meebey** [comment]
You can specify the room nickname on join using the /joinas command (see /help on the XMPP chat). By default it uses the nickname used for the XMPP connection. If it is the global nick instead the you have ran into a bug of smuxi-server 0.11.

**Comment by nbartels** [comment]
Thanks a lot, ```joinas``` solves the issue.

**Comment by meebey** [comment]
You are welcome.
