### ISSUE TITLE
Win7 can't paste

### ISSUE THREAD

**Issue by codrus** [meebey/smuxi#220]
The only text I can copy and paste into smuxi is text from its own text window. If I copy from my browser or from a text file and try to paste into smuxi, the paste option is there, but when you do it nothing happens.

Win7
v0.11.1 but also present in 0.11.0
##

**Comment by meebey** [comment]
Are you trying ctrl+v or right click in message entry (bottom) and select Paste?

**Comment by codrus** [comment]
Happens with both ctrl+v or right click menu.

**Comment by codrus** [comment]
It's working now. I changed nothing but yesterday and today it is working.  I'll let you know if the problem starts again, or you can close this ticket.

**Comment by meebey** [comment]
Closing this issue as it has not resurfaced.
