### ISSUE TITLE
Wish: Smuxi should load old logs when starting up

### ISSUE THREAD

**Issue by fsateler** [meebey/smuxi#224]
If smuxi engine shuts down for some reason, on next startup I would like smuxi to load up the last N lines from the channel log if it is available. It should probably at the same time annotate the exit/enter events.

This is especially useful when a remote instance is reset, as accessing remote logs is (apparently?) only possible by sshing into the remote host.

**Comment by knocte** [comment]
+1. I believe this is already in the roadmap though

**Comment by meebey** [comment]
This feature has already been implemented and is called persistent chat buffers and will be included in the upcoming 1.0 release, see http://smuxi.im/drafts/smuxi_1.0_release/

You probably want to give 1.0~rc3 a spin :)

**Comment by fsateler** [comment]
Excellent news! Now if only one had deb packages for the prereleases... ;)

Thanks!

On 6 May 2015 at 14:16, Mirco Bauer <notifications@github.com> wrote:

> This feature has already been implemented and is called persistent chat
> buffers and will be included in the upcoming 1.0 release, see
> http://smuxi.im/drafts/smuxi_1.0_release/
>
> You probably want to give 1.0~rc3 a spin :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meebey/smuxi/issues/224#issuecomment-99541777>.
>



-- 

Saludos,
Felipe Sateler

**Comment by meebey** [comment]
Implemented in 609cd5da95829d73c8bb9305d8e6af9d5dd65697
