### ISSUE TITLE
[1.0.1] Missing libraries

### ISSUE THREAD

**Issue by sagitter** [meebey/smuxi#242]
Hi,

why ```lib/db4o-net``` directory is empty? 
```db4o```, like ```SmartIrc4net```, libraries are required by compilation.

**Comment by meebey** [comment]
Have you used the tarball from the website? ArchLinux has packaged already AFAIK

**Comment by sagitter** [comment]
I downloaded https://github.com/meebey/smuxi/archive/1.0.1.tar.gz .

**Comment by sagitter** [comment]
This is the right tarball: https://smuxi.im/jaws/data/files/smuxi-1.0.1.tar.gz

**Comment by meebey** [comment]
Oh I will check if I can disable the tarballs for tags
