### ISSUE TITLE
Highlight words are being treated as case sensitive.

### ISSUE THREAD

**Issue by zoredache** [meebey/smuxi#243]
I have the pattern `zore` set in my highlight words.  If someone communicating me uses ZORE, or zoRE, or anything else other than `zore` then I will not get a highlight.

Please do one of the following.
- make globally insensitive.
- make it optionally globally case insensitive.
- or make it optional per-pattern.

IMO the best option would be to just apply `RegexOptions.IgnoreCase` to all highlightword patterns.  Since you have decided to escape everything I provide, you seem to be trying to make this user-friendly.  So make it more user-friendly, and make it case insensitive.  It is very annoying to have my attempts to do something like `/[aA][bB][cC]/` to get a case insensitive search escaped away, and also not be able to provide a pattern that would be case insensitive.

On method might be to permit passing regex options similar to `sed` at the end of the regex.

**Comment by meebey** [comment]
You are right, you can use regex but not provide regex options like /foo/i, I will look into this. By default it shouldn't be case sensitive, like regular highlight words, but be case insensitive.
