### ISSUE TITLE
Building smuxi from tar archive is not possible

### ISSUE THREAD

**Issue by doppioandante** [meebey/smuxi#273]
Hi, I'm building smuxi from the [source code](https://smuxi.im/jaws/data/files/smuxi-1.0.7.tar.gz) (version 1.0.7).
There are two issues that I have found so far:
 * autogen.sh is not included
 * all the dist-* targets apparently use git to retrieve a version string, but I don't think that git should be required as a dependency to build smuxi (moreover, there's no .git folder that it could use).

EDIT: I managed to build by patching Makefile.am and copying the autogen.sh file. The latter also uses git, but running `NOGIT=1 make dist-linux-static` avoid calling it.

One thing that I noticed is that I had to manually copy log4net and Nini inside the lib/ folder, but they should be easily found through `pkg-config`.

**Comment by meebey** [comment]
Release tarballs usually never contain autogen.sh as you only need to run ./configure and then make and make install. 

The dist-* make targets are for upstream packaging only.

log4net and nini are automatically detected via pkg-config

**Comment by doppioandante** [comment]
Thanks, I think I did something wrong with the configure step regarding log4net and nini, closing.
