### ISSUE TITLE
Don't use deprecated glade-sharp

### ISSUE THREAD

**Issue by City-busz** [meebey/smuxi#276]
Libglade is deprecated in favor of GtkBuilder since 2009:
https://mail.gnome.org/archives/devel-announce-list/2009-May/msg00003.html

Please port Smuxi from glade-sharp to GtkBuilder.

**Comment by Narrat** [comment]
Seems to be addressed with https://github.com/meebey/smuxi/commit/bf8cbfc4fb489e22ae48374127ced94621b69f9e
So this issue could be closed
