### ISSUE TITLE
Smuxi Website flagged by MalwareBytes as Trojan

### ISSUE THREAD

**Issue by pmraps** [meebey/smuxi#289]
Hello,

I was trying to access your website, smuxi.im, it's been quite a while, and got a weird message.

![2021-03-21 08_14_43-Blocked by Browser Guard - Brave](https://user-images.githubusercontent.com/43935667/111898440-00159b00-8a1e-11eb-95da-69c7b84f3cb7.png)

What is going on, please?
Best regards.

**Comment by knocte** [comment]
I can't reproduce this, and I've tried with 3 browsers: Chrome, Brave, Firefox.

**Comment by pmraps** [comment]
This was flagged by MalwareBytes, as you can see. But the funny thing is I click to continue to the site and Brave Browser also blocked it. So, after two blocks, I got suspicious.
I got there after creating exceptions, but it is being flagged. Maybe someone should tell something to MalwareBytes?

Thank you for answering.

**Comment by meebey** [comment]
Thanks for the report. I am pretty sure this is a false-positive that we have seen in the past because of the SmartIrcr4net library that is also used by "hacking software"... I will to try to reproduce it MalwareByte Browser Guard.

**Comment by meebey** [comment]
I can reproduce this issue by visiting smuxi.im with the Google Chrome browser and having MalwareBytes Browser Guard extension active. I will contact the vendor for clarification why it flags the site as "hosting trojans".

**Comment by pmraps** [comment]
I'm using Brave, but I suppose its the same...
Thank you.

**Comment by meebey** [comment]
The browser does not matter, as the warning comes through the MalwareBytes software.

I created a ticket with MalwareBytes and they removed the incorrect Trojan flag. Here their full response for reference:

> Thank you for taking the time to report this.  Our Researchers have reviewed this website and the block is being removed. Our apologies for any concern or inconvenience this caused you.

**Comment by meebey** [comment]
MalwareBytes has resolved the issue, I can load smuxi.im now without any warnings.
