### ISSUE TITLE
smuxi 1.2.1: I cannot save the settings

### ISSUE THREAD

**Issue by jeremyp3** [meebey/smuxi#296]
Hello,

since smuxi 1.2.1, I can't save the settings in the preferences. 
1. I go to preferences then interfaces
2. I change a value, for example: "Lines in scrollback
at this moment, I only have a close button, I don't have an ok or apply button like before. if I click on this close button and go back to preferences, nothing is saved.

I remind you that I use smuxi with an assistance tool (orca) under debian. it may be just an accessibility issue, you never know

I have the problem with the debian package and with the installation by make && make install

thanks for the help !

![Capture du 2023-05-06 16-17-42](https://user-images.githubusercontent.com/30219507/236630357-cf35030d-356f-4e61-af96-3c8e556154bc.png)

**Comment by meebey** [comment]
@jeremyp3 nice finding! The new interface is simplified in accordance with the GNOME human interface guidelines, so the "Close" button does save your changes, or is supposed to at least.

I could reproduce this bug and had to jump through multiple layers of abstraction which left me puzzled why every config change is lost/discarded but in the end, I could locate the buggy code and fix it. If you try Smuxi from the master branch it should work for you.

**Comment by jeremyp3** [comment]
I confirme, is fixed now !

thanks again !
