### ISSUE TITLE
please mark this as dead

### ISSUE THREAD

**Issue by iconoclasthero** [meebey/smuxi#302]
There're no debs
tHERE'S nothing in the repos
the packages req'd for building are not available
please mark this as fucking dead as dead so that no one else wastes time trying to compile 

i'm glad i installed all that mono shit a minute after timeshift took a snap.

**Comment by iconoclasthero** [comment]
hey, 302 is my area code.

**Comment by meebey** [comment]
Smuxi is packaged in NixOS and other Unixes. Installing and compiling it on other Linux is more complicated than it should be, this is mostly because of GTK# being removed, see #297
